FROM node:20-alpine AS development

WORKDIR /app

RUN apk add --no-cache wget

COPY package*.json turbo.json ./
COPY . .

RUN npm install

RUN npm run build --workspace=@challenge/notifications-service

EXPOSE 3004

CMD ["npm", "run", "dev", "--workspace=@challenge/notifications-service"]