FROM node:20-alpine AS development

WORKDIR /app

RUN apk add --no-cache wget

COPY package*.json turbo.json ./
COPY . .

RUN npm install

RUN npm run build --workspace=@challenge/api-gateway

EXPOSE 3001

CMD ["npm", "run", "dev", "--workspace=@challenge/api-gateway"]